channels:
  maya:
    id: 235835559
    label: Maya
    notifications:
      live: true
  alveussanctuary:
    id: 636587384
    label: AlveusSanctuary
    notifications:
      live: false # 24/7 anyways
  pjeweb:
    id: 60734874
    label: pjeweb
    notifications:
      live: true